# NUMPY ASSIGNMENT II

### Question 1: Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10. \


In [16]:
import numpy as np

# Create a vector of length 5 filled with arbitrary integers from 0 to 10

vector = np.random.randint(0, 11, size=5)


print(vector)

[ 6  0 10  8  1]


### Question 1: Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values​​except the first and last.


In [18]:
#vector with values ranging from 15 to 55

vector = np.arange(15, 56)

# print all values except the first and last

print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


### Question 1:Write a NumPy program to create a random array with 1000 elements and compute the average, variance, standard deviation of the array elements. 

In [33]:
# a random array with 1000 elements
array = np.random.rand(1000)

# calculate the average
avg = np.mean(array)

# calcuate the variance
var = np.var(array)

# calculate the standard deviation
std = np.std(array)

print("Average:", avg)
print("Variance:", var)
print("Standard deviation:", std)

Average: 0.501523869676229
Variance: 0.08348042648526575
Standard deviation: 0.2889297950805104


### Question 1:Write a NumPy program to calculate cumulative sum of the elements along a given axis, sum over rows for each of the 3 columns and sum over columns for each of the 2 rows of a given 3x3 array

In [38]:
# create 3x3 array
arr = np.array([[2, 4, 6],
                [1, 3, 8],
                [9, 8, 1]])

# compute cumulative sum along axis 1 (rows)
cumtsum_axis1 = np.cumsum(arr, axis=1)

# computing the  sum over rows for each of the 3 columns
sum_rows = np.sum(arr, axis=0)

# calculating sum over columns for each of the 2 rows
sum_cols = np.sum(arr, axis=1)

print("Original array:\n", arr)
print("Cumulative sum along axis 1:\n", cumtsum_axis1)
print("Sum over rows for each of the 3 columns:", sum_rows)
print("Sum over columns for each of the 2 rows:", sum_cols)

Original array:
 [[2 4 6]
 [1 3 8]
 [9 8 1]]
Cumulative sum along axis 1:
 [[ 2  6 12]
 [ 1  4 12]
 [ 9 17 18]]
Sum over rows for each of the 3 columns: [12 15 15]
Sum over columns for each of the 2 rows: [12 12 18]


### Question 1:Write a NumPy program to compute the multiplication of two given matrixes. 

Sample Matrix: 

[[1, 0], [0, 1]] 

[[1, 2], [3, 4]] 

In [40]:
# defining the given  matrices
matrix_1 = np.array([[1, 0], [0, 1]])
matrix_2 = np.array([[1, 2], [3, 4]])

# Compute the multiplication of the matrices
reslt = np.dot(matrix_1, matrix_2)

# Print the result
print("Matrix 1:\n", matrix_1)
print("Matrix 2:\n", matrix_2)
print("Result:\n", reslt)

Matrix 1:
 [[1 0]
 [0 1]]
Matrix 2:
 [[1 2]
 [3 4]]
Result:
 [[1 2]
 [3 4]]
